### ISSUE TITLE
Missing jodatime ZoneInfoMap

### ISSUE THREAD

**Issue by rholder** [rholder/esthree#17]
When the AWS region isn't known it starts trying to guess based on jodatime's ZoneInfoMap. But that file doesn't exist inside the binary and this appears:
```java
java.io.IOException: Resource not found: "org/joda/time/tz/data/ZoneInfoMap" ClassLoader: sun.misc.Launcher$AppClassLoader@2396649c
        at org.joda.time.tz.ZoneInfoProvider.openResource(ZoneInfoProvider.java:210)
        at org.joda.time.tz.ZoneInfoProvider.<init>(ZoneInfoProvider.java:127)
        at org.joda.time.tz.ZoneInfoProvider.<init>(ZoneInfoProvider.java:86)
        at org.joda.time.DateTimeZone.getDefaultProvider(DateTimeZone.java:514)
        at org.joda.time.DateTimeZone.getProvider(DateTimeZone.java:413)
        at org.joda.time.DateTimeZone.forID(DateTimeZone.java:216)
        at org.joda.time.DateTimeZone.getDefault(DateTimeZone.java:151)
        at org.joda.time.chrono.ISOChronology.getInstance(ISOChronology.java:79)
        at org.joda.time.DateTimeUtils.getChronology(DateTimeUtils.java:266)
        at org.joda.time.format.DateTimeFormatter.selectChronology(DateTimeFormatter.
        at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:
        at com.amazonaws.util.DateUtils.parseRFC822Date(DateUtils.java:193)
        at com.amazonaws.services.s3.internal.ServiceUtils.parseRfc822Date(ServiceUti
        at com.amazonaws.services.s3.internal.AbstractS3ResponseHandler.populateObjec
        at com.amazonaws.services.s3.internal.S3ObjectResponseHandler.handle(S3Object
        at com.amazonaws.services.s3.internal.S3ObjectResponseHandler.handle(S3Object
        at com.amazonaws.http.AmazonHttpClient.handleResponse(AmazonHttpClient.java:9
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.jav
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:46
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:295)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3714)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:114
        at com.github.rholder.esthree.command.Get$1.call(Get.java:113)
        at com.github.rholder.esthree.command.Get$1.call(Get.java:108)
        at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(Attem
        at com.github.rholder.retry.Retryer.call(Retryer.java:110)
        at com.github.rholder.esthree.command.Get.retryingGet(Get.java:108)
        at com.github.rholder.esthree.command.Get.call(Get.java:78)
        at com.github.rholder.esthree.cli.GetCommand.run(GetCommand.java:96)
        at com.github.rholder.esthree.Main.execute(Main.java:89)
        at com.github.rholder.esthree.Main.main(Main.java:42)
```
Let's add that to the build so we never see this again.

**Comment by rholder** [comment]
Fixed as of the 0.2.7 release.

**Comment by getindas** [comment]
I am using joda-time-2.9.6.jar. Still i am getting java.io.IOException: Resource not found: "org/joda/time/tz/data/ZoneInfoMap" ClassLoader: sun.misc.Launcher$AppClassLoader@2396649

Please suggest me how to resolve this issue.

**Comment by rdooley** [comment]
Specify a default aws region in your config.
